import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { api, apiBlob, type LoginResponse, type SessionUser } from './lib/api';
import { Activity, AlertTriangle, Archive, Bot, ChevronRight, CircleDollarSign, FileText, GraduationCap, LayoutDashboard, Menu, Package, Plus, QrCode, Search, Settings, ShieldCheck, Users, Wrench, X } from 'lucide-react';

type View='dashboard'|'students'|'assets'|'maintenance'|'inventory'|'finance'|'knowledge'|'assistant';
type Dashboard={students:number;staff:number;assets:number;maintenanceOpen:number;priorityMaintenance:number;overdueInvoices:number;overdueAmount:number;lowStockCount:number;lowStockItems:{id:string;name:string;quantity:string|number;minimumQty:string|number}[];totalExpenses:number};
type Asset={id:string;assetCode:string;name:string;category:string;location?:string|null;status:string;qrToken:string};
type Student={id:string;studentCode:string;firstName:string;lastName:string;class?:{name:string;level?:string|null}|null;guardians:{guardian:{firstName:string;lastName:string;phone?:string|null}}[]};
type Invoice={id:string;number:string;dueDate:string;totalAmount:string|number;paidAmount:string|number;status:string;student?:{studentCode:string;firstName:string;lastName:string}|null};
type Item={id:string;sku:string;name:string;category:string;unit:string;quantity:string|number;minimumQty:string|number;isLow:boolean;supplier?:{name:string}|null};
type Maintenance={id:string;title:string;priority:number;status:string;openedAt:string;asset?:{name:string;location?:string|null}|null};
type Knowledge={id:string;title:string;sourceType:string;mimeType?:string|null;createdAt:string;_count:{chunks:number}};

const nav:[View,string,any][]=[['dashboard','Vue d’ensemble',LayoutDashboard],['students','Élèves',GraduationCap],['assets','Ressources',Archive],['maintenance','Maintenance',Wrench],['inventory','Stock',Package],['finance','Finance',CircleDollarSign],['knowledge','Connaissances',FileText],['assistant','Assistant IA',Bot]];

export default function App(){
  const [user,setUser]=useState<SessionUser|null>(null); const [view,setView]=useState<View>('dashboard'); const [sidebar,setSidebar]=useState(true);
  useEffect(()=>{const raw=localStorage.getItem('schoolos_user'); if(raw) setUser(JSON.parse(raw));},[]);
  if(!user) return <Login onLogin={setUser}/>;
  const logout=()=>{localStorage.removeItem('schoolos_token');localStorage.removeItem('schoolos_user');setUser(null);};
  const CurrentIcon=nav.find(x=>x[0]===view)?.[2]??LayoutDashboard;
  return <div className="app-shell">
    <aside className={`sidebar ${sidebar?'':'collapsed'}`}><div className="brand"><div className="brand-mark"><Activity size={20}/></div>{sidebar&&<div><b>AI School OS</b><span>School Operating System</span></div>}</div>
      <nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)} title={label}><Icon size={18}/>{sidebar&&<span>{label}</span>}</button>)}</nav>
      <div className="sidebar-bottom">{sidebar&&<div className="tenant-chip"><ShieldCheck size={16}/><span><b>Groupe Atlas</b><small>Tenant sécurisé</small></span></div>}<button onClick={logout} className="logout">{sidebar?'Se déconnecter':'↪'}</button></div>
    </aside>
    <main className="main"><header className="topbar"><div className="title-group"><button className="icon-btn" onClick={()=>setSidebar(v=>!v)}><Menu size={19}/></button><div><div className="eyebrow">{view==='dashboard'?'DIRECTION':'AI SCHOOL OS'} · 2026–2027</div><h1>{view==='dashboard'?`Bonjour, ${user.firstName} 👋`:nav.find(x=>x[0]===view)?.[1]}</h1></div></div><div className="top-right"><div className="search-top"><Search size={16}/><input placeholder="Rechercher…"/></div><button className="icon-btn"><Settings size={18}/></button><div className="avatar">{user.firstName[0]}{user.lastName[0]}</div></div></header>
      {view==='dashboard'&&<DashboardPage onNavigate={setView}/>} {view==='students'&&<StudentsPage/>}{view==='assets'&&<AssetsPage/>}{view==='maintenance'&&<MaintenancePage/>}{view==='inventory'&&<InventoryPage/>}{view==='finance'&&<FinancePage/>}{view==='knowledge'&&<KnowledgePage/>}{view==='assistant'&&<AssistantPage/>}
    </main>
  </div>;
}

function Login({onLogin}:{onLogin:(u:SessionUser)=>void}){const [email,setEmail]=useState('director@atlas-school.ma');const [password,setPassword]=useState('Demo@12345');const [error,setError]=useState('');const [loading,setLoading]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{const r=await api<LoginResponse>('/auth/login',{method:'POST',skipAuth:true,body:JSON.stringify({email,password})});localStorage.setItem('schoolos_token',r.token);localStorage.setItem('schoolos_user',JSON.stringify(r.user));onLogin(r.user);}catch(e){setError(e instanceof Error?e.message:'Connexion impossible');}finally{setLoading(false);}};return <div className="login-page"><div className="login-orbit"><div className="brand-mark big"><Activity size={28}/></div><p className="eyebrow">AI SCHOOL OS</p><h1>Le système d’exploitation<br/>intelligent de votre école.</h1><p>Centraliser. Automatiser. Décider.</p></div><form className="login-card" onSubmit={submit}><div className="login-head"><div className="brand-mark"><Activity size={19}/></div><div><b>Connexion</b><span>Espace direction</span></div></div><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Mot de passe<input type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label>{error&&<div className="error">{error}</div>}<button className="primary wide" disabled={loading}>{loading?'Connexion…':'Entrer dans AI School OS'}</button><small className="muted">Démo locale · director@atlas-school.ma</small></form></div>}

function DashboardPage({onNavigate}:{onNavigate:(v:View)=>void}){const [data,setData]=useState<Dashboard|null>(null);const [err,setErr]=useState('');useEffect(()=>{api<{data:Dashboard}>('/dashboard/summary').then(r=>setData(r.data)).catch(e=>setErr(e.message));},[]);const cards=data?[['Élèves actifs',data.students.toLocaleString('fr-FR'),'Population active',GraduationCap],['Impayés',`${data.overdueAmount.toLocaleString('fr-FR')} DH`,`${data.overdueInvoices} facture(s)`,CircleDollarSign],['Équipements',data.assets.toString(),`${data.maintenanceOpen} maintenance(s)`,Archive],['Stock critique',data.lowStockCount.toString(),data.lowStockCount?'À traiter':'Tout va bien',Package]]:[];return <section className="page">{err&&<div className="error">{err}</div>}<div className="hero"><div><p className="eyebrow">AI MANAGEMENT BRIEF</p><h2>{data?`${data.priorityMaintenance+data.lowStockCount} signal(s) opérationnel(s) prioritaire(s).`:'Chargement des signaux…'}</h2><p>Une lecture synthétique des risques opérationnels, financiers et matériels de votre établissement.</p></div><button className="primary" onClick={()=>onNavigate('assistant')}><Bot size={18}/> Interroger l’IA</button></div><div className="grid kpis">{cards.map(([label,value,sub,Icon]:any)=><div className="card kpi" key={label}><div className="kpi-top"><span>{label}</span><Icon size={18}/></div><strong>{value}</strong><small>{sub}</small></div>)}</div><div className="grid split"><div className="card"><SectionTitle title="Alertes prioritaires" subtitle="Ce qui mérite votre attention maintenant"/><Insight tone="danger" title={`${data?.priorityMaintenance??'—'} maintenance(s) prioritaire(s)`} text="Vérifiez les incidents affectant la continuité ou les équipements critiques." onClick={()=>onNavigate('maintenance')}/><Insight tone="warn" title={`${data?.overdueInvoices??'—'} facture(s) en retard`} text={`${data?.overdueAmount?.toLocaleString('fr-FR')??'—'} DH restent à recouvrer.`} onClick={()=>onNavigate('finance')}/><Insight tone="info" title={`${data?.lowStockCount??'—'} article(s) sous seuil`} text="Préparez les demandes de réapprovisionnement." onClick={()=>onNavigate('inventory')}/></div><div className="card"><SectionTitle title="Décisions assistées" subtitle="Premières actions recommandées"/><Action text="Revoir le parc matériel" onClick={()=>onNavigate('assets')}/><Action text="Contrôler les impayés" onClick={()=>onNavigate('finance')}/><Action text="Vérifier les fournitures" onClick={()=>onNavigate('inventory')}/><Action text="Consulter les procédures" onClick={()=>onNavigate('knowledge')}/></div></div><div className="card ai-banner"><div className="assistant-icon"><Bot size={24}/></div><div><b>Votre copilote est prêt.</b><p>Posez une question en français ou en arabe. L’IA utilisera uniquement les données et outils autorisés pour votre compte.</p></div><button className="secondary" onClick={()=>onNavigate('assistant')}>Ouvrir l’assistant</button></div></section>}
function SectionTitle({title,subtitle}:{title:string;subtitle:string}){return <div className="section-title"><div><h3>{title}</h3><p>{subtitle}</p></div></div>}
function Insight({tone,title,text,onClick}:{tone:string;title:string;text:string;onClick:()=>void}){return <button className={`insight ${tone}`} onClick={onClick}><div><b>{title}</b><p>{text}</p></div><ChevronRight size={17}/></button>}
function Action({text,onClick}:{text:string;onClick:()=>void}){return <button className="action-row" onClick={onClick}><span>{text}</span><ChevronRight size={16}/></button>}

function StudentsPage(){const [rows,setRows]=useState<Student[]>([]);const [q,setQ]=useState('');useEffect(()=>{const t=setTimeout(()=>api<{data:Student[]}>(`/students${q?`?q=${encodeURIComponent(q)}`:''}`).then(r=>setRows(r.data)),250);return()=>clearTimeout(t);},[q]);return <section className="page"><PageHead eyebrow="ACADÉMIQUE" title="Élèves & responsables" text="Annuaire centralisé des élèves, classes et responsables légaux."/><div className="toolbar"><div className="search-box"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nom, code élève…"/></div><span className="muted">{rows.length} résultat(s)</span></div><div className="card table-card"><table><thead><tr><th>Élève</th><th>Code</th><th>Classe</th><th>Responsable</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td><b>{s.firstName} {s.lastName}</b></td><td>{s.studentCode}</td><td>{s.class?.name??'—'}</td><td>{s.guardians[0]?`${s.guardians[0].guardian.firstName} ${s.guardians[0].guardian.lastName}`:'—'}</td></tr>)}</tbody></table></div></section>}

function AssetsPage(){const [rows,setRows]=useState<Asset[]>([]);const [open,setOpen]=useState(false);const load=()=>api<{data:Asset[]}>('/assets').then(r=>setRows(r.data));useEffect(()=>{load()},[]);const showQr=async(id:string)=>{try{const blob=await apiBlob(`/assets/${id}/qr`);const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){alert(e instanceof Error?e.message:'QR indisponible')}};return <section className="page"><PageHead eyebrow="RESSOURCES" title="Parc équipements" text="Chaque actif possède un identifiant, une localisation et un QR Code de traçabilité." action={<button className="primary" onClick={()=>setOpen(true)}><Plus size={17}/> Ajouter</button>}/><div className="card table-card"><table><thead><tr><th>Actif</th><th>Catégorie</th><th>Lieu</th><th>État</th><th>QR</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td><b>{a.name}</b><small>{a.assetCode}</small></td><td>{a.category}</td><td>{a.location??'—'}</td><td><span className={`status ${a.status.toLowerCase()}`}>{a.status.replaceAll('_',' ')}</span></td><td><button className="icon-btn" onClick={()=>showQr(a.id)} title="Ouvrir le QR"><QrCode size={17}/></button></td></tr>)}</tbody></table></div>{open&&<AssetModal onClose={()=>setOpen(false)} onCreated={()=>{setOpen(false);load();}}/>}</section>}
function AssetModal({onClose,onCreated}:{onClose:()=>void;onCreated:()=>void}){const [name,setName]=useState('');const [code,setCode]=useState('');const [category,setCategory]=useState('Informatique');const [location,setLocation]=useState('');const [error,setError]=useState('');const [saving,setSaving]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{await api('/assets',{method:'POST',body:JSON.stringify({name,assetCode:code,category,location})});onCreated();}catch(e){setError(e instanceof Error?e.message:'Erreur')}finally{setSaving(false)}};return <Modal title="Nouvel équipement" onClose={onClose}><form onSubmit={submit} className="form"><label>Nom<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Dell Latitude 5440"/></label><div className="form-grid"><label>Code<input required value={code} onChange={e=>setCode(e.target.value)} placeholder="IT-006"/></label><label>Catégorie<input required value={category} onChange={e=>setCategory(e.target.value)}/></label></div><label>Localisation<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Salle informatique"/></label>{error&&<div className="error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Annuler</button><button className="primary" disabled={saving}>{saving?'Création…':'Créer'}</button></div></form></Modal>}

function MaintenancePage(){const [rows,setRows]=useState<Maintenance[]>([]);useEffect(()=>{api<{data:Maintenance[]}>('/maintenance').then(r=>setRows(r.data))},[]);return <section className="page"><PageHead eyebrow="OPÉRATIONS" title="Maintenance" text="Incidents, priorités et interventions rattachées aux ressources." action={<button className="primary"><Plus size={17}/> Nouvelle demande</button>}/><div className="card maintenance-list">{rows.map(m=><div className="maintenance-item" key={m.id}><div className={`priority p${m.priority}`}>{m.priority<=2?<AlertTriangle size={16}/>:<Wrench size={16}/>}</div><div className="grow"><b>{m.title}</b><span>{m.asset?.name??'Sans équipement'} · {m.asset?.location??'—'}</span></div><span className={`status ${m.status.toLowerCase()}`}>{m.status.replaceAll('_',' ')}</span><small>{new Date(m.openedAt).toLocaleDateString('fr-FR')}</small><ChevronRight size={16}/></div>)}</div></section>}

function InventoryPage(){const [rows,setRows]=useState<Item[]>([]);useEffect(()=>{api<{data:Item[]}>('/inventory').then(r=>setRows(r.data))},[]);const low=rows.filter(x=>x.isLow).length;return <section className="page"><PageHead eyebrow="LOGISTIQUE" title="Stocks" text="Consommables, seuils minimum et mouvements de stock."/><div className="mini-banner"><Package size={18}/><b>{low}</b><span>article(s) sous leur seuil minimum</span></div><div className="card table-card"><table><thead><tr><th>Article</th><th>Catégorie</th><th>Stock</th><th>Seuil</th><th>Fournisseur</th></tr></thead><tbody>{rows.map(i=><tr key={i.id}><td><b>{i.name}</b><small>{i.sku}</small></td><td>{i.category}</td><td className={i.isLow?'low-stock':''}>{i.quantity} {i.unit}</td><td>{i.minimumQty} {i.unit}</td><td>{i.supplier?.name??'—'}</td></tr>)}</tbody></table></div></section>}

function FinancePage(){const [summary,setSummary]=useState<any>(null);const [rows,setRows]=useState<Invoice[]>([]);useEffect(()=>{Promise.all([api<any>('/finance/summary'),api<{data:Invoice[]}>('/finance/invoices')]).then(([s,i])=>{setSummary(s.data);setRows(i.data)})},[]);return <section className="page"><PageHead eyebrow="FINANCE" title="Pilotage financier" text="Impayés, encaissements et dépenses de l’établissement."/><div className="grid kpis"><div className="card kpi"><span>Impayés</span><strong>{summary?`${summary.overdueAmount.toLocaleString('fr-FR')} DH`:'—'}</strong><small>{summary?.overdueInvoices??'—'} facture(s)</small></div><div className="card kpi"><span>Encaissements</span><strong>{summary?`${summary.totalPaid.toLocaleString('fr-FR')} DH`:'—'}</strong><small>Cumul enregistré</small></div><div className="card kpi"><span>Dépenses</span><strong>{summary?`${summary.totalExpenses.toLocaleString('fr-FR')} DH`:'—'}</strong><small>Cumul enregistré</small></div></div><div className="card table-card"><table><thead><tr><th>Facture</th><th>Élève</th><th>Échéance</th><th>Montant</th><th>Solde</th><th>Statut</th></tr></thead><tbody>{rows.map(i=><tr key={i.id}><td><b>{i.number}</b></td><td>{i.student?`${i.student.firstName} ${i.student.lastName}`:'—'}</td><td>{new Date(i.dueDate).toLocaleDateString('fr-FR')}</td><td>{Number(i.totalAmount).toLocaleString('fr-FR')} DH</td><td>{(Number(i.totalAmount)-Number(i.paidAmount)).toLocaleString('fr-FR')} DH</td><td><span className={`status ${i.status.toLowerCase()}`}>{i.status}</span></td></tr>)}</tbody></table></div></section>}

function KnowledgePage(){const [docs,setDocs]=useState<Knowledge[]>([]);const [q,setQ]=useState('');const [results,setResults]=useState<any[]>([]);const [title,setTitle]=useState('');const [content,setContent]=useState('');const [open,setOpen]=useState(false);const load=()=>api<{data:Knowledge[]}>('/knowledge').then(r=>setDocs(r.data));useEffect(()=>{load()},[]);const search=async()=>{if(!q.trim()){setResults([]);return}const r=await api<{data:any[]}>(`/knowledge/search?q=${encodeURIComponent(q)}`);setResults(r.data)};const add=async(e:FormEvent)=>{e.preventDefault();await api('/knowledge',{method:'POST',body:JSON.stringify({title,content,sourceType:'INTERNAL',mimeType:'text/plain'})});setTitle('');setContent('');setOpen(false);load();};return <section className="page"><PageHead eyebrow="CONNAISSANCE" title="Base documentaire" text="Politiques et procédures internes, indexées pour le RAG de l’assistant." action={<button className="primary" onClick={()=>setOpen(true)}><Plus size={17}/> Ajouter un document</button>}/><div className="card search-knowledge"><div className="search-box"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Rechercher une procédure…"/></div><button className="secondary" onClick={search}>Rechercher</button>{results.length>0&&<div className="knowledge-results">{results.map((r,i)=><div className="knowledge-result" key={i}><span className="score">{Math.round(r.score*100)}%</span><div><b>{r.title}</b><p>{r.content}</p></div></div>)}</div>}</div><div className="card table-card"><table><thead><tr><th>Document</th><th>Type</th><th>Chunks</th><th>Créé le</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td><b>{d.title}</b></td><td>{d.sourceType}</td><td>{d._count.chunks}</td><td>{new Date(d.createdAt).toLocaleDateString('fr-FR')}</td></tr>)}</tbody></table></div>{open&&<Modal title="Nouveau document" onClose={()=>setOpen(false)}><form onSubmit={add} className="form"><label>Titre<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Contenu<textarea required minLength={20} value={content} onChange={e=>setContent(e.target.value)} rows={9} placeholder="Procédure, règlement, note interne…"/></label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Annuler</button><button className="primary">Indexer</button></div></form></Modal>}</section>}

function AssistantPage(){const [message,setMessage]=useState('');const [answer,setAnswer]=useState('Bonjour. Je peux analyser les ressources, la maintenance, le stock, les impayés, les élèves et les procédures internes.');const [mode,setMode]=useState('');const [tool,setTool]=useState('');const [citations,setCitations]=useState<any[]>([]);const [loading,setLoading]=useState(false);const send=async()=>{if(!message.trim())return;setLoading(true);try{const r=await api<{data:{answer:string;mode:string;toolName:string|null;citations:any[]}}>('/ai/query',{method:'POST',body:JSON.stringify({message})});setAnswer(r.data.answer);setMode(r.data.mode);setTool(r.data.toolName??'');setCitations(r.data.citations??[]);setMessage('')}catch(e){setAnswer(e instanceof Error?e.message:'Erreur IA')}finally{setLoading(false)}};return <section className="page"><div className="assistant-header"><div><p className="eyebrow">AI COPILOT</p><h2>Assistant de direction</h2><p>Tool calling contrôlé, permissions tenant-scoped et accès documentaire RAG.</p></div><span className="secure-badge"><ShieldCheck size={16}/> Accès contrôlé</span></div><div className="chat card"><div className="chat-message ai"><div className="assistant-icon"><Bot size={20}/></div><div><b>AI School OS</b><p>{answer}</p><small>{mode}{tool?` · tool: ${tool}`:''}</small>{citations.length>0&&<div className="citations">{citations.map((c,i)=><span key={i}>Source {i+1}: {c.title}</span>)}</div>}</div></div><div className="suggestions">{['Quels équipements sont en réparation ?','Quels articles sont sous le seuil ?','Quels sont les impayés actuels ?','Que dit la procédure de déclaration de panne ?','Quels élèves correspondent au code ST-0001 ?'].map(s=><button key={s} onClick={()=>setMessage(s)}>{s}</button>)}</div><div className="chat-input"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Posez votre question…"/><button className="primary" disabled={loading} onClick={send}><Bot size={17}/>{loading?'Analyse…':'Envoyer'}</button></div></div></section>}

function PageHead({eyebrow,title,text,action}:{eyebrow:string;title:string;text:string;action?:any}){return <div className="page-head"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{text}</p></div>{action}</div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:any}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><h3>{title}</h3><p>AI School OS</p></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div>{children}</div></div>}
